//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trupanion.Pets.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetOwner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetOwner()
        {
            this.Pets = new HashSet<Pet>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PolicyNumber { get; set; }
        public Nullable<System.DateTime> PolicyDate { get; set; }
        public byte CountryId { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pet> Pets { get; set; }
    }
}
