//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trupanion.Pets.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Trupanion.Pets.Data.Entities;
    
    public partial class TrupanionEntities : DbContext
    {
        public TrupanionEntities()
            : base("name=TrupanionEntities")
        {
    	this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AnimalType> AnimalTypes { get; set; }
        public virtual DbSet<Breed> Breeds { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<PetOwner> PetOwners { get; set; }
    }
}
